import mongoose from "mongoose";
const videochema = mongoose.Schema(
  {
    videotitle: { type: String, required: true },
    filename: { type: String, required: true },
    filetype: { type: String, required: true },
    filepath: { type: String, required: true }, // Now stores Firebase Storage URL instead of local path
    filesize: { type: Number, required: true },
    videochanel: { type: String, required: true },
    description: { type: String, default: "" },
    category: { type: String, default: "General" },
    tags: { type: [String], default: [] },
    thumbnail: { type: String, default: "" },
    customThumbnailUrl: { type: String, default: "" },
    autoGeneratedThumbnailUrl: { type: String, default: "" },
    visibility: {
      type: String,
      enum: ["public", "private", "unlisted"],
      default: "public",
    },
    language: { type: String, default: "en" },
    Like: { type: Number, default: 0 },
    Dislike: { type: Number, default: 0 },
    views: { type: Number, default: 0 },
    uploader: { type: String },
    uploaderId: { type: mongoose.Schema.Types.ObjectId, ref: "user" },
    // Firebase Storage paths (for deletion purposes)
    _firebaseVideoPath: { type: String, default: "" },
    _firebaseThumbnailPath: { type: String, default: "" },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("videofiles", videochema);
