import mongoose from "mongoose";

const VideoSchema = new mongoose.Schema({
  videotitle: String,
  filename: String,
  filepath: String,
  filetype: String,
  filesize: String,
  videochanel: String,
  description: String,
  category: String,
  tags: [String],
  thumbnail: String,
  customThumbnailUrl: String,
  autoGeneratedThumbnailUrl: String,
  visibility: String,
  language: String,
  Like: Number,
  Dislike: Number,
  views: Number,
  uploader: String,
  uploaderId: String,
}, { timestamps: true, collection: "videofiles" });

export default mongoose.models.Video || 
mongoose.model("Video", VideoSchema, "videofiles");
