import Link from "next/link";
import Image from "next/image";
import { formatDistanceToNow } from "date-fns";
import { getPreviewUrl } from "@/lib/api";

interface RelatedVideosProps {
  videos?: Array<{
    _id: string;
    videotitle: string;
    videochanel: string;
    views: number;
    createdAt: string;
    filepath?: string;
    thumbnail?: string;
    customThumbnailUrl?: string;
    autoGeneratedThumbnailUrl?: string;
  }> | null;
  currentVideoId?: string;
}

export default function RelatedVideos({
  videos,
  currentVideoId,
}: RelatedVideosProps) {
  const list = (videos || []).filter((v) => v._id !== currentVideoId);

  if (list.length === 0) {
    return (
      <p className="text-sm text-gray-500">No related videos available.</p>
    );
  }

  return (
    <div className="space-y-2">
      {list.map((video) => {
        const previewUrl = getPreviewUrl(
          video.customThumbnailUrl,
          video.autoGeneratedThumbnailUrl,
          video.thumbnail,
          video.filepath
        );
        return (
          <Link
            key={video._id}
            href={`/watch/${video._id}`}
            className="flex gap-2 group"
          >
            <div className="relative w-40 aspect-video bg-gray-100 rounded overflow-hidden flex-shrink-0">
              <Image
                src={previewUrl}
                alt={video.videotitle}
                fill
                className="object-cover group-hover:scale-105 transition-transform duration-200"
              />
            </div>
            <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm line-clamp-2 group-hover:text-blue-600">
              {video.videotitle}
            </h3>
            <p className="text-xs text-gray-600 mt-1">{video.videochanel}</p>
            <p className="text-xs text-gray-600">
              {(video.views || 0).toLocaleString()} views • {formatDistanceToNow(new Date(video.createdAt))} ago
            </p>
          </div>
        </Link>
        );
      })}
    </div>
  );
}
