"use client";
import { useState } from "react";
import Link from "next/link";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { getPreviewUrl, formatVideoDate } from "@/lib/api";

export default function VideoCard({ video }: any) {
  const [thumbnailError, setThumbnailError] = useState(false);

  if (!video?._id) return null;

  const previewUrl = getPreviewUrl(
    video.customThumbnailUrl,
    video.autoGeneratedThumbnailUrl,
    video.thumbnail,
    video.filepath
  );

  const showPreviewImage = Boolean(
    previewUrl &&
      !thumbnailError &&
      previewUrl !== "/default-thumbnail.svg"
  );

  return (
    <Link href={`/watch/${video._id}`} className="group block">
      <div className="space-y-3">
        <div className="relative aspect-video rounded-lg overflow-hidden bg-gray-100">
          {showPreviewImage ? (
            <img
              src={previewUrl}
              alt={video.videotitle || "Video thumbnail"}
              loading="lazy"
              onError={() => setThumbnailError(true)}
              className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-200"
            />
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center gap-3 bg-slate-100 px-4 text-center">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-200 text-2xl font-semibold text-slate-600">
                {video?.videotitle?.[0]?.toUpperCase() || "V"}
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-800 line-clamp-2">
                  {video?.videotitle || "Untitled video"}
                </p>
                <p className="text-xs text-slate-500">
                  Thumbnail unavailable
                </p>
              </div>
            </div>
          )}
        </div>
        <div className="flex gap-3">
          <Avatar className="w-9 h-9 flex-shrink-0">
            <AvatarFallback>{video?.videochanel?.[0] || "?"}</AvatarFallback>
          </Avatar>
          <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm line-clamp-2 group-hover:text-blue-600">
              {video?.videotitle}
            </h3>
            <p className="text-sm text-gray-600 mt-1">{video?.videochanel}</p>
            <p className="text-sm text-gray-600">
              {(video?.views || 0).toLocaleString()} views • {formatVideoDate(video?.createdAt)}
            </p>
          </div>
        </div>
      </div>
    </Link>
  );
}
