"use client";
import { useState } from "react";
import Link from "next/link";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { getPreviewUrl, formatVideoDate } from "@/lib/api";

export default function VideoCard({ video }: any) {
  const [thumbnailError, setThumbnailError] = useState(false);

  if (!video?._id) return null;

  const previewUrl = getPreviewUrl(
    video.customThumbnailUrl,
    video.autoGeneratedThumbnailUrl,
    video.thumbnail,
    video.filepath
  );

  const showPreviewImage = Boolean(
    previewUrl &&
      !thumbnailError &&
      previewUrl !== "/default-thumbnail.svg"
  );

  return (
    <Link href={`/watch/${video._id}`} className="group block">
      <div className="space-y-3">
        <div className="relative aspect-video rounded-lg overflow-hidden bg-gray-100">
          {showPreviewImage ? (
            <img
              src={previewUrl}
              alt={video.videotitle || "Video thumbnail"}
              loading="lazy"
              onError={() => setThumbnailError(true)}
              className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-200"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-slate-950 via-slate-900 to-sky-700 px-4 text-center">
              <div className="flex flex-col items-center gap-4">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-white/10 ring-1 ring-white/20">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-8 w-8 text-white"
                  >
                    <path
                      d="M10 8.5L16.5 12L10 15.5V8.5Z"
                      fill="currentColor"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeOpacity="0.2"
                      strokeWidth="2"
                    />
                  </svg>
                </div>
                <p className="max-w-[80%] text-sm font-semibold text-white line-clamp-2">
                  {video?.videotitle || "Untitled video"}
                </p>
              </div>
            </div>
          )}
        </div>
        <div className="flex gap-3">
          <Avatar className="w-9 h-9 flex-shrink-0">
            <AvatarFallback>{video?.videochanel?.[0] || "?"}</AvatarFallback>
          </Avatar>
          <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm line-clamp-2 group-hover:text-blue-600">
              {video?.videotitle}
            </h3>
            <p className="text-sm text-gray-600 mt-1">{video?.videochanel}</p>
            <p className="text-sm text-gray-600">
              {(video?.views || 0).toLocaleString()} views • {formatVideoDate(video?.createdAt)}
            </p>
          </div>
        </div>
      </div>
    </Link>
  );
}
