"use client";
import Link from "next/link";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { getPreviewUrl, formatVideoDate } from "@/lib/api";
import Image from "next/image";

export default function VideoCard({ video }: any) {
  if (!video?._id) return null;

  const previewUrl = getPreviewUrl(
    video.customThumbnailUrl,
    video.autoGeneratedThumbnailUrl,
    video.thumbnail,
    video.filepath
  );

  return (
    <Link href={`/watch/${video._id}`} className="group block">
      <div className="space-y-3">
        <div className="relative aspect-video rounded-lg overflow-hidden bg-gray-100">
          {previewUrl ? (
            <Image
              src={previewUrl}
              alt={video.videotitle}
              fill
              className="object-cover group-hover:scale-105 transition-transform duration-200"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center text-gray-400 text-sm">
              No preview
            </div>
          )}
        </div>
        <div className="flex gap-3">
          <Avatar className="w-9 h-9 flex-shrink-0">
            <AvatarFallback>{video?.videochanel?.[0] || "?"}</AvatarFallback>
          </Avatar>
          <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm line-clamp-2 group-hover:text-blue-600">
              {video?.videotitle}
            </h3>
            <p className="text-sm text-gray-600 mt-1">{video?.videochanel}</p>
            <p className="text-sm text-gray-600">
              {(video?.views || 0).toLocaleString()} views •{" "}
              {formatVideoDate(video?.createdAt)}
            </p>
          </div>
        </div>
      </div>
    </Link>
  );
}
