import { formatDistanceToNow } from "date-fns";

export function getBackendUrl(): string {
  const raw =
    process.env.NEXT_PUBLIC_API_URL ||
    process.env.NEXT_PUBLIC_BACKEND_URL ||
    process.env.BACKEND_URL ||
    (process.env.NODE_ENV === "development" ? "http://localhost:5000/api" : "/api");

  if (!raw) {
    return "";
  }

  const normalized = raw.replace(/\/+$/, "");
  if (/\/api($|\/)/i.test(normalized)) {
    return normalized.replace(/\/+$/, "");
  }
  return `${normalized}/api`;
}

export function getVideoUrl(filepath?: string): string {
  if (!filepath) return "";
  const normalized = filepath.replace(/\\/g, "/");
  
  // If it's already a full URL (HTTP/HTTPS), return as-is (Firebase Storage URL)
  if (normalized.startsWith("http://") || normalized.startsWith("https://")) {
    return normalized;
  }
  
  // Fallback for legacy local paths (local dev/old deployments)
  const apiBase = getBackendUrl().replace(/\/$/, "");
  const backendRoot = apiBase.replace(/\/api$/i, "");
  const root =
    backendRoot ||
    (typeof window !== "undefined" ? window.location.origin : "") ||
    apiBase.replace(/\/$/, "");

  let publicPath = normalized;
  const uploadsIndex = normalized.indexOf("/uploads/");
  if (uploadsIndex >= 0) {
    publicPath = normalized.slice(uploadsIndex + 1);
  } else if (normalized.startsWith("/uploads/")) {
    publicPath = normalized.slice(1);
  } else if (normalized.startsWith("uploads/")) {
    publicPath = normalized;
  }

  const path = publicPath.startsWith("/") ? publicPath.slice(1) : publicPath;
  return `${root}/${path}`;
}

export function getPreviewUrl(
  customThumbnailUrl?: string,
  autoGeneratedThumbnailUrl?: string,
  legacyThumbnail?: string,
  filepath?: string
): string {
  const normalizedCustom = customThumbnailUrl?.trim();
  if (normalizedCustom) {
    return normalizedCustom.startsWith("http")
      ? normalizedCustom
      : getVideoUrl(normalizedCustom);
  }

  const normalizedAuto = autoGeneratedThumbnailUrl?.trim();
  if (normalizedAuto) {
    return normalizedAuto.startsWith("http")
      ? normalizedAuto
      : getVideoUrl(normalizedAuto);
  }

  const normalizedLegacy = legacyThumbnail?.trim();
  if (normalizedLegacy) {
    return normalizedLegacy.startsWith("http")
      ? normalizedLegacy
      : getVideoUrl(normalizedLegacy);
  }

  return "/default-thumbnail.svg";
}

export function formatVideoDate(date?: string | Date): string {
  if (!date) return "Recently";
  try {
    const d = new Date(date);
    if (Number.isNaN(d.getTime())) return "Recently";
    return `${formatDistanceToNow(d)} ago`;
  } catch {
    return "Recently";
  }
}

export const PLANS = {
  FREE: { name: "FREE", price: 0, watchLimitMinutes: 5 },
  BRONZE: { name: "BRONZE", price: 10, watchLimitMinutes: 7 },
  SILVER: { name: "SILVER", price: 50, watchLimitMinutes: 10 },
  GOLD: { name: "GOLD", price: 100, watchLimitMinutes: Infinity },
} as const;

export const SOUTH_INDIA_STATES = [
  "Tamil Nadu",
  "Kerala",
  "Karnataka",
  "Andhra Pradesh",
  "Telangana",
];
