export function isValidHttpUrl(value?: string): boolean {
  if (!value || typeof value !== "string") return false;
  try {
    const url = new URL(value.trim());
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

export function isCloudinaryUrl(value?: string): boolean {
  if (!isValidHttpUrl(value)) return false;
  try {
    const url = new URL(value!.trim());
    return /cloudinary\.com/i.test(url.hostname);
  } catch {
    return false;
  }
}

export function hasThumbnail(video: any): boolean {
  if (!video || typeof video !== "object") return false;
  return [video.thumbnail, video.customThumbnailUrl, video.autoGeneratedThumbnailUrl].some(
    (value) => typeof value === "string" && value.trim().length > 0
  );
}

export function isPlayableVideo(video: any): boolean {
  if (!video || typeof video !== "object") return false;
  const filepath = typeof video.filepath === "string" ? video.filepath.trim() : "";
  if (!filepath || !isValidHttpUrl(filepath)) return false;
  if (!hasThumbnail(video)) return false;
  return true;
}

export function deriveCloudinaryVideoThumbnailUrl(videoUrl: string): string | null {
  if (!isCloudinaryUrl(videoUrl)) return null;

  try {
    const url = new URL(videoUrl.trim());
    if (!url.pathname.includes("/video/upload/")) return null;
    url.pathname = url.pathname.replace("/video/upload/", "/image/upload/");
    url.pathname = url.pathname.replace(/\.(mp4|mov|webm|mkv|avi|flv|ogg|ogv|m4v)(?:$|\?)/i, ".jpg");
    return url.toString();
  } catch {
    return null;
  }
}

export async function verifyRemoteUrlAccessible(url: string): Promise<boolean> {
  const normalized = url?.trim();
  if (!normalized || !isValidHttpUrl(normalized)) return false;

  try {
    const response = await fetch(normalized, {
      method: "HEAD",
      cache: "no-store",
    });
    if (response.ok) return true;
    if (response.status === 405 || response.status === 501 || response.status === 403) {
      const fallback = await fetch(normalized, {
        method: "GET",
        cache: "no-store",
      });
      return fallback.ok;
    }
    return false;
  } catch {
    return false;
  }
}

export function normalizeVideoDocument(doc: any): any {
  if (!doc) return doc;
  if (typeof doc.toObject === "function") {
    return doc.toObject();
  }
  return { ...doc };
}

export function normalizeVideoList(docs: any[]): any[] {
  return (docs || []).map((doc) => normalizeVideoDocument(doc));
}
