import dotenv from 'dotenv';
dotenv.config();
import { connectDatabase } from '../config/database.js';
import Video from '../Modals/video.js';
import {
  deleteVideoFromCloudinary,
  deleteThumbnailFromCloudinary,
} from '../services/cloudinaryUpload.js';

function extractCloudinaryPublicId(url) {
  try {
    const u = new URL(url);
    // Find /upload/ in pathname and take remainder
    const idx = u.pathname.indexOf('/upload/');
    if (idx === -1) return null;
    let rest = u.pathname.slice(idx + '/upload/'.length);
    // remove version like v123456789/
    rest = rest.replace(/^v\d+\//, '');
    // remove extension
    rest = rest.replace(/\.[a-zA-Z0-9]+$/, '');
    return rest;
  } catch (e) {
    return null;
  }
}

async function run() {
  await connectDatabase();
  const title = 'CI Test Video 2';
  const doc = await Video.findOne({ videotitle: title });
  if (!doc) {
    console.log(JSON.stringify({ found: false, message: 'Video not found' }, null, 2));
    process.exit(0);
  }

  const report = {
    videoId: doc._id.toString(),
    videoTitle: doc.videotitle,
    deletionStatus: 'pending',
    cloudinaryVideo: {
      publicId: doc.cloudinaryVideoPublicId || null,
      attempt: false,
      status: 'not-attempted',
    },
    cloudinaryThumbnail: {
      publicId: doc.cloudinaryThumbnailPublicId || null,
      attempt: false,
      status: 'not-attempted',
    },
  };

  // Attempt delete video asset
  try {
    let publicId = doc.cloudinaryVideoPublicId;
    if (!publicId && typeof doc.filepath === 'string' && /cloudinary.com/.test(doc.filepath)) {
      publicId = extractCloudinaryPublicId(doc.filepath);
      if (publicId) report.cloudinaryVideo.publicId = publicId;
    }

    if (publicId) {
      report.cloudinaryVideo.attempt = true;
      try {
        await deleteVideoFromCloudinary(publicId);
        report.cloudinaryVideo.status = 'deleted';
      } catch (e) {
        report.cloudinaryVideo.status = 'error: ' + (e && e.message ? e.message : String(e));
      }
    } else {
      report.cloudinaryVideo.status = 'no-remote-video';
    }
  } catch (e) {
    report.cloudinaryVideo.status = 'error: ' + (e && e.message ? e.message : String(e));
  }

  // Attempt delete thumbnail asset
  try {
    let thumbId = doc.cloudinaryThumbnailPublicId;
    if (!thumbId && typeof doc.customThumbnailUrl === 'string' && /cloudinary.com/.test(doc.customThumbnailUrl)) {
      thumbId = extractCloudinaryPublicId(doc.customThumbnailUrl);
      if (thumbId) report.cloudinaryThumbnail.publicId = thumbId;
    }
    if (!thumbId && typeof doc.autoGeneratedThumbnailUrl === 'string' && /cloudinary.com/.test(doc.autoGeneratedThumbnailUrl)) {
      thumbId = extractCloudinaryPublicId(doc.autoGeneratedThumbnailUrl);
      if (thumbId && !report.cloudinaryThumbnail.publicId) report.cloudinaryThumbnail.publicId = thumbId;
    }

    if (thumbId) {
      report.cloudinaryThumbnail.attempt = true;
      try {
        await deleteThumbnailFromCloudinary(thumbId);
        report.cloudinaryThumbnail.status = 'deleted';
      } catch (e) {
        report.cloudinaryThumbnail.status = 'error: ' + (e && e.message ? e.message : String(e));
      }
    } else {
      report.cloudinaryThumbnail.status = 'no-remote-thumb';
    }
  } catch (e) {
    report.cloudinaryThumbnail.status = 'error: ' + (e && e.message ? e.message : String(e));
  }

  // Delete DB doc
  try {
    const deleted = await Video.findByIdAndDelete(doc._id);
    report.deletionStatus = deleted ? 'deleted' : 'not-found-after-attempt';
  } catch (e) {
    report.deletionStatus = 'error: ' + (e && e.message ? e.message : String(e));
  }

  console.log(JSON.stringify(report, null, 2));
  process.exit(0);
}

run().catch((e) => {
  console.error('Script error:', e && e.message ? e.message : e);
  process.exit(1);
});
