#!/usr/bin/env node
const mongoose = require("mongoose");
const Video = require("../Modals/video.js");

const uri = process.env.DB_URL || process.argv[2];
if (!uri) {
  console.error("Usage: DB_URL must be provided via env or as first argument");
  process.exit(1);
}

(async () => {
  try {
    await mongoose.connect(uri, {});
    console.log("Connected to MongoDB");

    const samples = [
      {
        videotitle: "Sample Video 1",
        filename: "sample1.mp4",
        filepath: "uploads/sample1.mp4",
        filetype: "video/mp4",
        filesize: 12345,
        videochanel: "Demo Channel",
        description: "Sample video inserted by seed script",
        category: "General",
        tags: [],
        thumbnail: "",
        customThumbnailUrl: "",
        autoGeneratedThumbnailUrl: "",
        visibility: "public",
        language: "en",
        Like: 0,
        Dislike: 0,
        views: 0,
        uploader: "seed",
      },
    ];

    const created = await Video.insertMany(samples);
    console.log("Inserted", created.length, "videos into videofiles collection");
    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
})();
