import fs from "fs/promises";
import path from "path";
import ffmpeg from "fluent-ffmpeg";
import ffmpegStatic from "ffmpeg-static";
import video from "../Modals/video.js";
import { normalizeVideoList, normalizeFilePath } from "../utils/normalize.js";

const ffmpegPath = ffmpegStatic;
if (ffmpegPath) {
  ffmpeg.setFfmpegPath(ffmpegPath);
}

async function ensureThumbnailDir() {
  const thumbnailsDir = path.resolve("uploads", "thumbnails");
  await fs.mkdir(thumbnailsDir, { recursive: true });
  return thumbnailsDir;
}

async function generateAutoThumbnail(videoFilePath) {
  if (!videoFilePath) {
    throw new Error("Missing video file path for thumbnail generation");
  }
  const absoluteVideoPath = path.isAbsolute(videoFilePath)
    ? videoFilePath
    : path.resolve(videoFilePath);

  const thumbnailsDir = await ensureThumbnailDir();
  const sourceStats = await fs.stat(absoluteVideoPath);
  if (!sourceStats.isFile()) {
    throw new Error("Video file not found for thumbnail generation");
  }

  const filename = path.basename(videoFilePath, path.extname(videoFilePath));
  const outputFilename = `${filename}-${Date.now()}.png`;
  const outputPath = path.join(thumbnailsDir, outputFilename);

  return new Promise((resolve, reject) => {
    ffmpeg(absoluteVideoPath)
      .screenshots({
        timestamps: ["1.5"],
        filename: outputFilename,
        folder: thumbnailsDir,
        size: "640x360",
      })
      .on("end", () => {
        resolve(normalizeFilePath(path.join("uploads", "thumbnails", outputFilename)));
      })
      .on("error", (error) => {
        reject(error);
      });
  });
}

export const uploadvideo = async (req, res) => {
  const videoFile = req.files?.file?.[0];
  if (!videoFile) {
    return res.status(400).json({ message: "Please upload a valid video file" });
  }

  const tags = typeof req.body.tags === "string"
    ? req.body.tags.split(",").map((tag) => tag.trim()).filter(Boolean)
    : Array.isArray(req.body.tags)
    ? req.body.tags
    : [];

  const thumbnailFile = req.files?.thumbnailFile?.[0];
  const thumbnailUrl = typeof req.body.thumbnail === "string" ? req.body.thumbnail.trim() : "";
  const customThumbnailUrl = thumbnailFile
    ? normalizeFilePath(thumbnailFile.path)
    : thumbnailUrl;

  let autoGeneratedThumbnailUrl = "";
  if (!customThumbnailUrl) {
    try {
      autoGeneratedThumbnailUrl = await generateAutoThumbnail(normalizeFilePath(videoFile.path));
    } catch (error) {
      console.error("Thumbnail generation failed:", error);
    }
  }

  try {
    const file = new video({
      videotitle: req.body.videotitle,
      filename: videoFile.originalname,
      filepath: normalizeFilePath(videoFile.path),
      filetype: videoFile.mimetype,
      filesize: videoFile.size,
      videochanel: req.user?.channelname || req.body.videochanel || "Unknown Channel",
      uploader: req.user?.name || req.body.uploader || "Unknown",
      uploaderId: req.user?._id,
      description: req.body.description || "",
      category: req.body.category || "General",
      tags,
      thumbnail: customThumbnailUrl || autoGeneratedThumbnailUrl || "",
      customThumbnailUrl: customThumbnailUrl || "",
      autoGeneratedThumbnailUrl: autoGeneratedThumbnailUrl || "",
      visibility: req.body.visibility || "public",
      language: req.body.language || "en",
    });
    await file.save();
    return res.status(201).json({ message: "File uploaded successfully", video: file });
  } catch (error) {
    console.error("Upload error:", error);
    return res.status(500).json({ message: "Something went wrong" });
  }
};

export const getallvideo = async (req, res) => {
  try {
    const files = await video.find().sort({ createdAt: -1 });
    return res.status(200).json(normalizeVideoList(files));
  } catch (error) {
    console.error("Get videos error:", error);
    return res.status(500).json({ message: "Something went wrong" });
  }
};

export const getVideoById = async (req, res) => {
  try {
    const file = await video.findById(req.params.id);
    if (!file) return res.status(404).json({ message: "Video not found" });
    const normalized = normalizeVideoList([file])[0];
    return res.status(200).json(normalized);
  } catch (error) {
    console.error("Get video by id error:", error);
    return res.status(500).json({ message: "Something went wrong" });
  }
};

export const updateVideo = async (req, res) => {
  const { id } = req.params;
  try {
    const update = {};
    const allowed = [
      "videotitle",
      "description",
      "category",
      "tags",
      "visibility",
      "language",
      "customThumbnailUrl",
    ];
    for (const k of allowed) {
      if (req.body[k] !== undefined) update[k] = req.body[k];
    }

    // If thumbnail file uploaded, prefer it
    if (req.files?.thumbnailFile?.[0]) {
      update.customThumbnailUrl = normalizeFilePath(req.files.thumbnailFile[0].path);
    }

    const updated = await video.findByIdAndUpdate(id, { $set: update }, { new: true });
    if (!updated) return res.status(404).json({ message: "Video not found" });
    return res.status(200).json({ message: "Updated", video: updated });
  } catch (error) {
    console.error("Update video error:", error);
    return res.status(500).json({ message: "Something went wrong" });
  }
};

export const deleteVideo = async (req, res) => {
  const { id } = req.params;
  try {
    const doc = await video.findByIdAndDelete(id);
    if (!doc) return res.status(404).json({ message: "Video not found" });
    // attempt remove file and thumbnails if present
    try {
      if (doc.filepath) await fs.unlink(path.resolve(normalizeFilePath(doc.filepath))).catch(() => {});
      if (doc.customThumbnailUrl) await fs.unlink(path.resolve(normalizeFilePath(doc.customThumbnailUrl))).catch(() => {});
      if (doc.autoGeneratedThumbnailUrl) await fs.unlink(path.resolve(normalizeFilePath(doc.autoGeneratedThumbnailUrl))).catch(() => {});
    } catch (e) {
      console.warn("Failed to remove media files for deleted video:", e.message || e);
    }
    return res.status(200).json({ message: "Deleted" });
  } catch (error) {
    console.error("Delete video error:", error);
    return res.status(500).json({ message: "Something went wrong" });
  }
};

export async function migrateLegacyThumbnails() {
  try {
    const legacyVideos = await video.find({
      thumbnail: { $nin: [null, undefined, ""] },
      customThumbnailUrl: { $in: [null, undefined, ""] },
    });

    await Promise.all(
      legacyVideos.map(async (doc) => {
        doc.customThumbnailUrl = doc.thumbnail;
        await doc.save();
      })
    );
  } catch (error) {
    console.error("Legacy thumbnail migration failed:", error);
  }
}

export async function generateMissingThumbnails() {
  try {
    const videosWithoutThumbnail = await video.find({
      customThumbnailUrl: { $in: [null, undefined, ""] },
      autoGeneratedThumbnailUrl: { $in: [null, undefined, ""] },
      thumbnail: { $in: [null, undefined, ""] },
    });

    for (const doc of videosWithoutThumbnail) {
      try {
        if (!doc.filepath) continue;
        const autoGeneratedThumbnailUrl = await generateAutoThumbnail(normalizeFilePath(doc.filepath));
        doc.autoGeneratedThumbnailUrl = autoGeneratedThumbnailUrl;
        doc.thumbnail = autoGeneratedThumbnailUrl;
        await doc.save();
      } catch (error) {
        console.error(`Failed to generate thumbnail for video ${doc._id}:`, error.message || error);
      }
    }
  } catch (error) {
    console.error("Missing thumbnail generation failed:", error);
  }
}
