export function normalizeFilePath(filepath) {
  if (!filepath) return "";
  return filepath.replace(/\\/g, "/");
}

export function normalizeVideoDoc(doc) {
  if (!doc) return doc;
  const obj = doc.toObject ? doc.toObject() : { ...doc };
  if (obj.filepath) obj.filepath = normalizeFilePath(obj.filepath);
  if (obj.customThumbnailUrl) obj.customThumbnailUrl = normalizeFilePath(obj.customThumbnailUrl);
  if (obj.autoGeneratedThumbnailUrl) obj.autoGeneratedThumbnailUrl = normalizeFilePath(obj.autoGeneratedThumbnailUrl);
  if (obj.thumbnail) obj.thumbnail = normalizeFilePath(obj.thumbnail);
  return obj;
}

export function normalizeVideoList(docs) {
  return (docs || []).map((d) => normalizeVideoDoc(d));
}
